### ISSUE TITLE
Wish list / todo list for ComputeSharp[.D2D1]

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#225]
As requested:

* D2D pixel shader source generator should have more validation. For example, if `[D2DInputSimple(3)]` is specified, there should be an error when `[D2DInputCount(n)]` for `n < 4`
* Not sure if you validate that `[D2DRequiresScenePosition]` requires that the shader be compiled for ... well, it might require ps_4_0 or ps_5_0, but ps_4_0_level_9_1 and probably 9_3 will not work.
* Casting operators for `float4` etc. between `Vector4` etc.. This way I can pull values out of my shader consts and do math with them on the C# side. Right now I'm resorting to adding properties that use `Unsafe.As<>()`
* Abilty to use `with` syntax either on shaders (`ID2D1PixelShader`) or its consts struct. Right now if I just want to change one value I have to specify all of the values to the constructor. (maybe this is an `[AutoConstructor]` request, or maybe another attribute is needed)
  * Thankfully you can do whatever you like with a constants struct, even define it as a `record`, but you can't with a shader struct. Hence why I usually have a nested `Constants` struct where I put all my values.
* For the love of all that is holy, just drop `Interop` from the `D2D1Interop` name 🤣
* _probably more to come_

**Comment by rickbrew** [comment]
* Some kind of `[IgnoredByShaderGenerator]` attribute so I can add methods, etc. to an `ID2D1PixelShader`. This would help for adding helper methods that help with loading the shader (`ID2D1EffectContext.LoadPixelShader()`) and for setting the constant buffer (via `ID2D1DrawInfo::SetPixelShaderConstantBuffer()`)
  * My scenario is creating an `IEffectPixelShader` interface, so you'd have `struct MyShader : ID2D1PixelShader, IEffectPixelShader { ... }`. Not entirely sure if this would work with the dependency/package firewalls we've discussed, but even if not this could support the source-generator-for-PDN-plugins we've also discussed.

**Comment by rickbrew** [comment]
* If the primitives in ComputeSharp.dll worked for real, that would be so useful. `float4`, `float4x4`, etc.

**Comment by rickbrew** [comment]
* Ability to write helper methods distributed in DLLs. Let's say I want to publish a nuget package with a bunch of helper methods for shaders. I could tag methods with (e.g.) `[HlslHelper]` and the CS generator would compile it to HLSL and included it as an embedded resource with the `.hlsli` extension. It wouldn't generate the byte code. Then, if I use that -- while compiling a different DLL, mind you -- in an `ID2D1PixelShader` (and maybe this'd work for any other type of shader, not just D2D), it would do the equivalent of `#include` on the associated `.hlsli`

**Comment by Sergio0694** [comment]
So to recap:

- [X] Validation for D2D attributes.
- [ ] `[D2DRequiresScenePosition]` works for all target profiles, so no validation needed.
- [X] Casting operators for `float` <-> `Vector4` etc. are there already.
- [X] Using the `with` syntax on shaders is supported if you don't make them readonly.
- [X] The package is now just `.D2D`, yes 😆
- [X] The `[IgnoredByShaderGeneration]` bit has been addressed already (we went with explicit interface implementations).
- [ ] Supporting primitives on the CPU is not doable, as discussed on Discord.
- [ ] Same for intrinsics.
- [ ] Distributing shader helpers in DLLs would be a whole other feature that should have its own issue. Also this is actually supported already (though with a different mechanism) in the main **ComputeSharp** package.

Closing this one 🙂

**Comment by rickbrew** [comment]
> So to recap:
> ...
> * [ ]  `[D2DRequiresScenePosition]` works for all target profiles, so no validation needed.

Pretty sure this doesn't work on the `_level_9_1` or `_level_9_3` targets, which is why I raised it

**Comment by Sergio0694** [comment]
I just tried to compile this and it worked:

```csharp
[D2DInputCount(1)]
[D2DInputSimple(0)]
[D2DRequiresScenePosition]
[D2DEmbeddedBytecode(D2D1ShaderProfile.PixelShader40Level91)]
[AutoConstructor]
public partial struct InvertEffect2 : ID2D1PixelShader
{
    /// <inheritdoc/>
    public float4 Execute()
    {
        float4 color = D2D.GetInput(0);
        float2 position = D2D.GetScenePosition().XY;
        float3 rgb = Hlsl.Saturate(1.0f - color.RGB);

        rgb.XY *= position;

        return new(rgb, 1);
    }
}
```

Same with `_level_9_3` as well (and also tested all others for good measure).

I suspect maybe you might've confused that with some other change in your shader that was causing the error? Was this before I fixed the diagnostics to display the actual error message from the compiler in the output window? 🤔

**Comment by rickbrew** [comment]
Hmm there's definitely something that didn't work on _9_1. I'll have to try it again and see what real error I actually get. And yeah it was before the generator would give me real errors, it was always just that NullRef exception.

**Comment by Sergio0694** [comment]
I see. Yeah I suspect it might've been something else then, maybe a specific other intrinsic that's not supported there?
