### ISSUE TITLE
3.0 release tracking

### ISSUE THREAD

**Issue by Sergio0694** [Sergio0694/ComputeSharp#598]
This issue tracks all changes for the upcoming 3.0 major release.

### Features and changes
- [x] Target .NET 8
- [x] Remove all downlevel TFMs
- [x] Introduce `IComputeShaderDescriptor<T>` API (like with D2D1 shaders)
- [x] Make dispatch threads mandatory for DX12 compute shaders
- [x] #588
- [x] #551
- [x] #462
- [x] Use static abstracts in interfaces for all descriptor interfaces
- [x] Add support for primary constructors in all shader types
- [x] Add support for primary constructors for resource types
- [x] Switch DX12 generator to use `IndentedTextWriter`

### Breaking changes
- [x] Remove `[AutoConstructor]` and generator
- [x] Remove `[ShaderMethod]` and generator (and infrastructure)
